language: julia
os:
- linux
julia:
- 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
sudo: required
before_script:
- julia -e 'import Pkg; Pkg.add(Pkg.PackageSpec(url="https://github.com/JuliaPackaging/BinaryBuilder.jl",
  rev="master"))'
- julia -e 'import Pkg; Pkg.add("BinaryProvider")'
script:
- julia build_tarballs.jl
deploy:
  provider: releases
  api_key:
    secure: tE4EXsWKKk5w7SxycbnJ3WwteLT0qD/Rdw1OeW/qkfZ1w2xo909/581Pcsrb9LNONo2y7qhsBWS02TKEgk+0ioi1QYoC0W7T+TErB+LsXYh7Thm/gOrGJwBumU07WM4E8z7FROTJ0Pt3RRjyHvDMEgJrvUSB39gg8LSIPKQbjSyD2sKf+gAuRMu86JvWEftcUoiY38jKH0bxiHvkv5+I/4gbJKXdyy2bY6WHlnXdZaduxIonXoL6RJk++io9ADjH5B5rvO4AIt/1b5Kw916iJgyOIWj6UJWZuSylHhti1D2r5XjKh+t+0m/p2vh+HEQQqwR94DBeEEz/oRecBhN2uaxcMVPfUN1Z2NV5qOzsld2mt20QFWoyuVGQXth29gkLK6wpCvewfjnVrSBWCvIl2Ue9CjNhR6z8khu9uOW4YsqrsGjdkkOgiAR57vZYhFuGzy4EZ2MLDLZa+4Akt1MOAmIR6q+LW/KPVHWM6bwn6KUTH8HNX9uafsGrfWq64P3rn3BSb+AkV/Z54mNcHdOsSMOek6vQ/VTSaNtrFjBWZ1LigZB96zbWDz1pGyR9Z5rjyEuH8Z0WJ2x3XE4oZN+PiQy4P2zMkRd2Dq73gGJHhpzbDtPtlc6xjsHJY03qSeykAMveMhWhG4O8sogBhA2zsCr62grFLWPinr/rO0QgIZo=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: leo60228/ImageMagickBuilder
    tags: true
